apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-lb # deployment name
  labels:
    app: redis-lb # deployment label
spec:
  selector:
    matchLabels:
      app: redis-lb # which pods is the deployment managing, as defined by the pod template
  template: # pod template
    metadata:
      labels:
        app: redis-lb 
    spec:  
      containers:
      - name:  redis-lb # Container name 
        image: maguec/haproxy-tcp:variableports #repo/image:tag
#### uncomment the following two lines while you are setting up your 
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
####
        imagePullPolicy: Always # IfNotPresent # Always pull image
        resources:
          limits:
            cpu: "3000m"
            memory: "1024Mi"
          requests:
            cpu: "3000m"
            memory: "256Mi"
        ports:  
        - containerPort: 2112 # exposed container port for haproxy stats
          protocol: TCP
        - containerPort: 16379 # exposed container port to the RES database
          protocol: TCP
        env:
          - name: HAPROXY_UPSTREAM_HOSTS  
            value: "172.30.6.123:12252,172.30.232.184:14233" # comma separated <host>:<port> pairs
          - name: HAPROXY_LISTEN_PORT
            value: "16379"
          # - name: HAPROXY_STATS_USER
          #   value: "/opt/redislabs/redis-lb/config/logback.xml"
          # - name: HAPROXY_STATS_PASSWORD
          #   value: "/opt/redislabs/redis-lb/config/logback.xml"
              
---
apiVersion: v1
kind: Service
metadata:
  name: redis-lb-service       # name should not be 'redis-lb' 
spec:
  type: ClusterIP
  ports:
    - port: 16379
      targetPort: 16379
  selector:
    app: redis-lb
---
apiVersion: v1
kind: Service
metadata:
  name: redis-lb-stats-service       # name should not be 'redis-lb' 
spec:
  type: ClusterIP
  ports:
    - port: 2112
      targetPort: 2112
  selector:
    app: redis-lb