apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-memtier
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: read-memtier
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: read-memtier
    spec:
# comment out the following lines if you want to limit the pod scheduling on a specific pool
#      nodeSelector:
#        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: benchmark
        image: redislabs/memtier_benchmark #:b1b1d10
        # args: ["-d", "100", "-n", "20000000", "--pipeline=2", "-a", "$(REDIS_PASSWORD)", "-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)"]
        args: ["--key-pattern=R:R", "--test-time=720", "-x", "100", "--ratio=0:1", "-t","$(NUM_THREADS)", "-c", "$(NUM_CLIENTS)", "--pipeline=2", "-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)", "-a", "$(REDIS_PASSWORD)"]
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
         - name: NUM_THREADS
           value: "2"
         - name: NUM_CLIENTS
           value: "2"
         - name: REDIS_PORT
           value: "10000"
         - name: REDIS_SERVER
           value: "twem-lb-svc"
         - name: REDIS_PASSWORD
           valueFrom:
                secretKeyRef:
                  key: password
                  name: redb-primary1
